name: Publish to npm

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ensure Node.js version 16 or higher is used
        registry-url: 'https://registry.npmjs.org/'  # npm registry URL

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run tests (optional but recommended before publishing)
    - name: Run tests
      run: npm test

    # Step 5: Check if the version already exists in npm
    - name: Check if version exists on npm
      run: |
        VERSION=$(node -p "require('./package.json').version")
        npm info @adovelopers/logado@$VERSION || echo "Version not published"

    # Step 6: Publish to npm if the version does not exist
    - name: Publish to npm
      if: success() && steps.check_version.outputs.version != 'Version not published'
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use npm authentication token from GitHub secrets
